name = "Internet Weblog"
license = "MIT"
licenselink = "https://github.com/jnjosh/internet-weblog/blob/master/LICENSE.md"
description = "A personal, minimal blog theme for Hugo."
homepage = "http://jnjosh.com"
tags = ["blog", "personal", "minimal", "microblog", "photoblog", "linkblog"]
features = ["Microblog", "Photoblog", "Blog", "Flickr Photo Stream", "Personal Blog", "Link Blog"]
version = 1.0
min_version = 0.14

[author]
  name = "Josh Johnson"
  homepage = "http://jnjosh.com"
